import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { cookies } from "next/headers";
import getClient from "./lib/mongodb";

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Local",
  description: "Generated by create next app",
};

// Define proper types for chat items
type ChatItem = {
  _id: string;
  Chat: {
    title: string;
  };
};

type FormattedChatItem = {
  title: string;
  id: string;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
  const client = await getClient();
  const db = client.db("bro-code");
  const collection = db.collection("Chat");
  const items = await collection
    .find(
      {},
      {
        projection: {
          _id: { $toString: "$_id" },
          "Chat.title": 1,
        },
      }
    )
    .toArray();

  const finalItems: FormattedChatItem[] = items
    .sort((a: ChatItem, b: ChatItem) => {
      const idA = a._id.toString();
      const idB = b._id.toString();
      return idB.localeCompare(idA); // Sort in descending order (most recent first)
    })
    .map((item: ChatItem) => ({
      title: item.Chat.title,
      id: item._id,
    }));

  return (
    <html lang="en">
      <body className={`${ubuntu.variable}  antialiased`}>
        <SidebarProvider defaultOpen={defaultOpen} >
          <AppSidebar prop={finalItems} />
          <main className="bg-[#333]">
            <SidebarTrigger className="text-gray-300 hover:bg-[#333] hover:text-white cursor-pointer" />
            {children}
            <footer className="fixed bottom-0 w-full text-center pb-2">
              <p className="text-[10px] text-white">
                © {new Date().getFullYear()} Bro Code. Developed By{" "}
                <a
                  href={"https://github.com/minbanyartalahtaw"}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:underline">
                  dumark
                </a>
              </p>
            </footer>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}